# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
